site_name: IronMachine4's Blog
site_url: https://IronMachine4.github.io
site_author: 李姜俊(IronMachine4)

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep orange
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep orange
  language: zh
  icon: 
    logo: material/notebook
  features:
    - navigation.path
    - content.code.copy
    - search.suggest
plugins:
  - search
markdown_extensions:
  - extra
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      auto_title: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra_javascript:
  - javascripts/extra.js
  - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/javascripts/extra.js  # extra的cdn
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js #Latex支持
  - https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js #忘了
nav:
  - 首页: index.md
  - 算法竞赛知识点: 
    - 数据结构:
      - 链表: algo/ds/list.md
      - 并查集: algo/ds/dsu.md
      - 线段树:
        - 吉司机线段树: algo/ds/sgt-beats.md
      - 可持久化数据结构:
        - 可持久化数据结构简介: algo/ds/persistent.md
        - 可持久化线段树: algo/ds/persistent-sgt.md
    - 动态规划:
      - 序列 DP: algo/dp/arr-dp.md
      - 动态 DP: algo/dp/ddp.md
      - DP 优化:
        - 翻转递推方向: algo/dp/opt/reverse-dp-order.md
    - 图论: 
      - 最小斯坦纳树: algo/graph/steiner-tree.md
    - 数学:
      - 数论:
        - 二次剩余: algo/math/number-theory/quad-residue.md
        - 拓展欧几里得算法: algo/math/number-theory/exgcd.md
        - 中国剩余定理: algo/math/number-theory/crt.md
        - 狄利克雷卷积: algo/math/number-theory/dirichlet.md
        - 杜教筛: algo/math/number-theory/du.md
  - 比赛题解: 
    - NOI2026 省选线上冬令营: comp/noi-2026-sx-online-wc.md